<a href="https://colab.research.google.com/github/esn73/lab_python/blob/master/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

필요한 라이브러리 모듈 임포트

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## np.ndarray 클래스 속성들(properties) 복습

In [4]:
# 모든 원소가 1.0으로 이루어진 (3, 4) 모양의 2차원 배열 생성
array = np.ones((3, 4))

In [5]:
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
type(array)

numpy.ndarray

In [9]:
array.dtype # 배열의 원소에 데이터 타입

dtype('float64')

In [10]:
array.shape # 배열의 각 축(axis)를 따라서 있는 원소들의 개술 만들어진 튜플

(3, 4)

In [12]:
array.size # 배열의 모든 원소들의 개수

12

In [13]:
array.ndim # 배열의 차원의 개수. 배열의 축(axis)의 개수. (3차원배열-2차원이 여러개 쌓여있는것)

2

In [14]:
# [1, 6) 1이상 6미만 범위의 정수들로 이루어진 1차원 배열
array = np.arange(1, 6)
print(array)

[1 2 3 4 5]


In [15]:
print('dtype:', array.dtype)
print('shpae:', array.shape) # axis를 따라서 원소가 몇개 있는지 
print('size:',  array.size) # 전체 원소의 개수
print('ndim:', array.ndim) # 1차원

dtype: int64
shpae: (5,)
size: 5
ndim: 1


In [17]:
# [1, 25) 범위의 정수들로 이루어진 (2, 3, 4) shape의 3차원 배열
array = np.arange(1, 25).reshape((2, 3, 4)) # 행3, 열4인 2차원 배열 2개 [[]] 
print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [18]:
print('dtype:', array.dtype)
print('shpae:', array.shape)
print('size:',  array.size)
print('ndim:', array.ndim)

dtype: int64
shpae: (2, 3, 4)
size: 24
ndim: 3


np.ndarray의 indexing

* Python의 list 인덱스 사용 방법: `list[i][j][k]...`
* numpy ndarray 인덱스 사용 방법:
    * `array[i][j][k]...`
    * `array[i, j, k, ...]`
    

In [19]:
print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [20]:
print(array[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(array[0][1])

[5 6 7 8]


In [22]:
print(array[0][1][2])

7


In [23]:
print(array[0, 1, 2])

7


# np.ndarray slicing

---


## 1차원 배열 slicing

In [24]:
np.random.seed(1)
array = np.random.rand(10)
print(array)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [28]:
# [1:5) 범위의 원소들로 이루어진 ndarray
print(array[1:5])

[7.20324493e-01 1.14374817e-04 3.02332573e-01 1.46755891e-01]


In [29]:
# 배열엣 첫 3개의 원소로 이루어진 ndarray
print(array[:3]) # array [0:3]- 시작 인덱스 0은 생략가능

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [ ]:
# 배열에서 마지막 3개의 원소로 이루어진 ndarray
print(array[-3:]) # slicing에서 end index를 생략하면 끝까지를 선택

In [ ]:
print(array[:]) # slicing start와 end index 모두를 생략하면 처음부터 끝까지 선택

## 2차원 배열 slicing

In [32]:
array = np.arange(1, 21).reshape((4,5))
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
# 행은 [1, 3) 열은 [1, 4) 범위로 slicing
print(array[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [36]:
# 첫 2개 열을 선택. 행은 모두 선택, 열은 [0, 2) 범위로 slicing
print(array[:, :2])

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [37]:
# 첫 2개 행을 선택 행은 [0,2) 범위로 slicing, 열은 모두 선택.
print(array[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 3차원 배열 slicing

In [38]:
array = np.arange(1, 61).reshape((3, 4, 5))
print(array)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [39]:
print(array[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


slicing vs indexing

In [40]:
print(array[:1, :, :]) #> slicing의 결과 3-d 배열

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [41]:
print(array[0]) #> indexing의 결과: 2-d 배열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [43]:
print(array[:, :, :2]) #> (3, 4, 2) shape의 3-d 배열

[[[ 1  2]
  [ 6  7]
  [11 12]
  [16 17]]

 [[21 22]
  [26 27]
  [31 32]
  [36 37]]

 [[41 42]
  [46 47]
  [51 52]
  [56 57]]]


# np.ndarray 모양(shape) 변형 

## `np.ndarray.reshape(shape)`

In [45]:
arr_1d = np.arange(1, 13)
print(arr_1d) #> 1-d 배열

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [51]:
# 1차원 배열을 (3, 4) shpae을 갖는 2-d 배열로 변형
arr_2d = arr_1d.reshape((3, 4))
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
# 1-d 배열을 2-d 배열로 변환할 때 행의 개수만 결정되면 열의 개수는 자동을 결정됨.
print(arr_1d.reshape((3, -1))) # 자동으로 계산이 되는 1개 차운의 원소 개수는 -1로 대체할 수 있음

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [54]:
# 1-d 배열을 2-d 배열로 변환할 때 열의 개수만 결정되면 행의 개수는 자동을 결정됨.
print(arr_1d.reshape((-1, 4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
# 2-d ndarray -> 1-d ndarray
result = arr_2d.reshape((3*4,)) # 3*4 원소 1개인 tuple로 전달
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [58]:
result = arr_2d.reshape(3*4) # shape을 정수로 전달.
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
